language: python
cache: pip

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build
  - docker-compose run app pipenv run lint
  - docker-compose run app pipenv run test
  - docker build -t u6kapps/investment-horse-racing-trader -f Dockerfile.production .

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker tag u6kapps/investment-horse-racing-trader u6kapps/investment-horse-racing-trader:$TRAVIS_TAG;
      docker push u6kapps/investment-horse-racing-trader;
    else
      echo skip docker push;
    fi

notifications:
  slack:
    secure: gRNFCWKmPqMPedgcH2AXMV7mwsBrSE7bdk0pilVoYzsDb/3m9KwRBxTfUy50jG9I1790fxiKdnPBFmhSHYARF2pJj717vOoc/DCXcOlH8pUKDA/S4t8Pp64Z6W5yDnjnO3cmPz1cU2E37o1R2aJ4TkondIw3IpuoiuJgxzZfXD0x5TNoLtJ8zxYg50lOwNpQ0ugjfOEjpLqaUtE7bHHjQ2KDlP1THYlKxKoSTghr2Fx9d+9X6gSwe09owVYqsaiVOfhj/MSFJfyjoMwWsxDGHphyKO4q7kILw7AOJvcO/6qUZeHRIshZ4AmakKfCSSdtBTWlwS8XG7S98dEZoFa0yx8DcrLzNtGiLmbgmGmXZtyZ8JTwNHDp5JXRFw5C7/wwT6LZ7Vmi45j4Q7yH6bh9D86XrJFsoQFpM+Xtx1J8Tw6u79IwZI4qeq+1JqfIo6KkZCqrCb6EOB7/psuqJZz7hRPL8bSw+uPyf1EluyCRIadMNrEttqLG2e8WEqWmi2ovOd6/4dQxpLTRjWP2a5Qh9LRiK2ZeCofbNg0PLyYRKulXGzJLA7FCTd2FT44re+mrnYXyDKK3ObMfI/SwYuAvlPEGOJjj/AcsUVb4b1ar0r5Fp2WuPYlGwIvMuyVXpZSfwjJMr4jp4HooLzuTqSZIN0xd3Ahv9+B7M6eEEn/sRRg=
