language: python
cache: pip

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build
  - docker-compose run app pipenv run lint
  - docker-compose run app pipenv run test
  - docker build -t u6kapps/investment-horse-racing-trader -f Dockerfile.production .

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker tag u6kapps/investment-horse-racing-trader u6kapps/investment-horse-racing-trader:$TRAVIS_TAG;
      docker push u6kapps/investment-horse-racing-trader;
    else
      echo skip docker push;
    fi
