version: '3'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    environment:
      - "TZ=Asia/Tokyo"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "API_PREDICT_URL=${API_PREDICT_URL}"
      - "API_PREDICT_AUTH_USER=${API_PREDICT_AUTH_USER}"
      - "API_PREDICT_AUTH_PASSWORD=${API_PREDICT_AUTH_PASSWORD}"
    ports:
      - "5000:5000"
    depends_on:
      - "db"

  db:
    image: postgres:12
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"

  crawler_db:
    image: postgres:12
    volumes:
      - "./tests/data:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=${CRAWLER_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${CRAWLER_DB_PASSWORD}"
      - "POSTGRES_DB=${CRAWLER_DB_DATABASE}"
